19-rails-forms-part-1/taco-tracker/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get "/", to: "application#homepage"
  get "/about_us", to: "application#about", as: "about"
  get "/hello/:name", to: "application#hello", as: "hello"
  # ^.             ^.               ^                   ^
  # HTTP Verb.    PATH            controller#method   helper_prefix
  
  # get "/tacos", to: "tacos#index"
  # get "/tacos/:id", to: "tacos#show", as: "taco"
  resources :tacos, only: [:index, :show, :new, :create]
  # get "/hi_dave", to: "tacos#index"
end

19-rails-forms-part-1/taco-tracker/app/controllers/tacos_controller.rb
class TacosController < ApplicationController


    def index
        if params["vegetarian"] == "true"
            @tacos = Taco.is_vegetarian?(true)
        elsif params["vegetarian"] == "false"
            @tacos = Taco.is_vegetarian?(false)
        else 
            @tacos = Taco.all
        end
    end

    def show
        id = params[:id]
        @taco = Taco.find(id)
        render :show
    end

    def new
        @taco = Taco.new
        # render :new
    end

    def create
        # name = params[:taco][:name]
        # vegetarian = params[:taco][:vegetarian]
        # price = params[:taco][:price]
        new_taco = Taco.create(taco_params)
        redirect_to taco_path(new_taco.id) # load "www.myapp.com/tacos/27"
        # redirect_to "/tacos/#{new_taco.id}"
    end

    private

    def taco_params
        params.require(:taco).permit(:name, :price, :vegetarian)
    end

end

19-rails-forms-part-1/taco-tracker/app/views/tacos/index.html.erb
<h1>Index Page</h1>


<!-- <form action="/tacos" method="GET">

    <input type="radio" name="vegetarian" value="true">
    <label>Only vegetarian</label>
    <input type="radio" name="vegetarian" value="false">
    <label>Only meat</label>
    <input type="radio" name="vegetarian" value="all">
    <label>All tacos</label>

    <input type="submit" value="Filter">

</form> -->

<%= form_tag tacos_path, method: "GET" do %>
    <%= radio_button_tag 'vegetarian', 'true' %>
    <%= label_tag "Only Vegetarian" %>
    <%= radio_button_tag 'vegetarian', 'false' %>
    <%= label_tag "Only Meat" %>
    <%= radio_button_tag 'vegetarian', 'all' %>
    <%= label_tag "All Tacos" %>
    <%= submit_tag "Filter" %>
<% end %>

<ul>
    <% @tacos.each do |taco| %>
        <li><%= link_to "#{taco.display_name}: #{taco.vegetarian}", taco_path(taco.id) %></li>
    <% end %>
</ul>


<%= link_to "Create a Taco", new_taco_path %>

19-rails-forms-part-1/taco-tracker/app/views/tacos/new.html.erb
<%= form_for @taco do |f| %>
    <%= f.label :name, "Taco Name" %>
    <%= f.text_field :name %>
    <%= f.label :price %>
    <%= f.number_field :price, min: 0, step: 0.01 %>
    <%= f.label :vegetarian %>
    <%= f.select :vegetarian, [true, false] %>
    <%= f.submit "Make a Taco" %>
<% end %>

19-rails-forms-part-1/taco-tracker/app/views/tacos/show.html.erb
<h1>Detail Page</h1>

<div>Name: <%= @taco.display_name %></div>
<div>Price: <%= number_to_currency(@taco.price) %></div>
<div>Vegetarian?:  <%= @taco.vegetarian %></div>


<%= link_to "All Tacos", tacos_path %>