27-CSS/taco-tracker/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get "/", to: "application#homepage", as: "homepage"
  get "/about", to: "application#about", as: "about"
  get "/hello/:name", to: "application#hello", as: "hello"
  # ^.             ^.               ^                   ^
  # HTTP Verb.    PATH            controller#method   helper_prefix
  
  get "/login", to: "sessions#login"
  post "/login", to: "sessions#process_login"
  get "/logout", to: "sessions#logout"
  # get "/tacos", to: "tacos#index"
  # get "/tacos/:id", to: "tacos#show", as: "taco"
  resources :tacos
  resources :restaurants, only: [:index, :show]
  # get "/hi_dave", to: "tacos#index"
end

27-CSS/taco-tracker/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

27-CSS/taco-tracker/app/models/ingredient.rb
class Ingredient < ApplicationRecord
    has_many :taco_ingredients
    has_many :tacos, through: :taco_ingredients
end

27-CSS/taco-tracker/app/models/restaurant.rb
class Restaurant < ApplicationRecord
    has_many :tacos

    def display_name_and_city
        return "#{self.name} - #{self.city}"
    end
end

27-CSS/taco-tracker/app/models/taco.rb
class Taco < ApplicationRecord

    belongs_to :restaurant

    has_many :taco_ingredients
    has_many :ingredients, through: :taco_ingredients

    # validates :name, presence: true, uniqueness: {case_sensitive: false}
    # validates :price, presence: true, numericality: {greater_than: 0, less_than_or_equal_to: 20}
    # validates_uniqueness_of :name,
    #     :message => Proc.new { |taco, data|
    #         "#{taco.name} has already been taken"
    #     }
    validates :vegetarian, inclusion: [true, false]
    
    def display_name
        return self.name.titlecase
    end

    def self.is_vegetarian?(bool_veg)
        # Taco.all.select do |taco|
        #     taco.vegetarian? == bool_veg
        # end
        Taco.where(vegetarian: bool_veg)
    end

    def veg_color
        self.vegetarian ? "title veggie" : "title not_veggie"
    end
end

27-CSS/taco-tracker/app/models/taco_ingredient.rb
class TacoIngredient < ApplicationRecord

    belongs_to :taco
    belongs_to :ingredient
    
end

27-CSS/taco-tracker/app/models/user.rb
class User < ApplicationRecord
end

27-CSS/taco-tracker/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user # call this in a view

    def homepage
        render :homepage
    end

    def about
        # render(:about)
    end

    def hello
        @cat_name = params[:name]
        @great_things_about_cats = ["They're fluffy", "They're cute", "They snuggle"]
        render :hello
    end

    def current_user
        @current_user = User.find(session[:user_id])
    end


end

27-CSS/taco-tracker/app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end
end

27-CSS/taco-tracker/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def login

    end

    def process_login
        # get the userrname from the form
        username = params[:username]
        # see if that username matches a user in our database
        user = User.find_by(username: username)
        if user 
            # log in that user
            session[:user_id] = user.id

            redirect_to tacos_path
        else 
            flash.now[:error] = "No user found with that name"
            # FLASH: if you redirect
            # FLASH.NOW if you render
            render :login
        end
    end

    def logout
        session.clear
        redirect_to login_path
    end

end

27-CSS/taco-tracker/app/controllers/tacos_controller.rb
class TacosController < ApplicationController

    before_action :find_taco, only: [:show, :edit, :update, :destroy]


    def index
        if params["vegetarian"] == "true"
            @tacos = Taco.is_vegetarian?(true)
        elsif params["vegetarian"] == "false"
            @tacos = Taco.is_vegetarian?(false)
        else 
            @tacos = Taco.all
        end
    end

    def show
        # cookies["favorite_taco"] = "Bacon Lovers' Supreme"
        cookies["last_visited"] = @taco.name
        session["secret_favorite"] = "Broccoli and cheese taco"
        render :show
    end

    def new
        @taco = Taco.new
        # render :new
    end

    def create
        # name = params[:taco][:name]
        # vegetarian = params[:taco][:vegetarian]
        @taco = Taco.new(taco_params)
        if @taco.valid?
            @taco.save
            redirect_to taco_path(@taco.id) # load "www.myapp.com/tacos/27"
        else
            render :new
        end
        # redirect_to "/tacos/#{new_taco.id}"
    end

    def edit
    end

    def update
        @taco.update(taco_params)
        if @taco.valid?
            redirect_to taco_path(@taco.id)
        else
            render :edit
        end
    end

    def destroy
        @taco.destroy
        redirect_to tacos_path
    end

    private

    def taco_params
        params.require(:taco).permit(:name, :vegetarian, :price, :restaurant_id, :ingredient_ids => [])
    end

    def find_taco
        @taco = Taco.find(params[:id])
    end

end

27-CSS/taco-tracker/app/helpers/application_helper.rb
module ApplicationHelper
end

27-CSS/taco-tracker/app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

27-CSS/taco-tracker/app/helpers/sessions_helper.rb
module SessionsHelper
end

27-CSS/taco-tracker/app/helpers/tacos_helper.rb
module TacosHelper
end

27-CSS/taco-tracker/app/views/application/about.html.erb
<h2>Taco Tracker App made by 2 Commit 2 Git</h2>

<h4>Tacos for everyone!</h4>

27-CSS/taco-tracker/app/views/application/hello.html.erb
<h1>Hello <%= @cat_name.upcase %></h1>


<ul>
    <% @great_things_about_cats.each do |fact| %>
        <li><%= fact %></li>
    <% end %>
</ul>

27-CSS/taco-tracker/app/views/application/homepage.html.erb
<h1>Welcome to our taco-tracker!</h1>


<!-- <a href="/about">About this page</a> -->
<!-- <a href="/hello/petey">Hello Petey</a>
<a href="/hello/ella">Hello Ella</a> -->
<nav class="navbar" role="navigation" aria-label="main-navigation">
    <%= link_to "About This Page", about_path %>
    <%= link_to "Hello Petey", hello_path("Petey") %>
    <%= link_to "Hello Ella", hello_path("Ella") %>
</nav>

27-CSS/taco-tracker/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Taco Tracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.0/css/bulma.min.css"> 
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
  </head>

  <body>
    <% unless controller_name == "sessions" && action_name == "login" %>

        <nav class="navbar is-danger">
          <div class="navbar-menu">
            <%= link_to "Home", tacos_path, class: "navbar-item" %>
            <%= link_to "About", about_path, class: "navbar-item" %>
            
      <% if session[:user_id] %>
              <%= link_to "Create a Taco", new_taco_path, class: "navbar-item" %>
              <div class="navbar-end">
              <%= link_to "Log out", logout_path, class: "navbar-item" %>
              </div>
          <% else %>

              <div class="navbar-end">
              <%= link_to "Log In", login_path, class: "navbar-item"  %>
              </div>
          <% end %>
          </div>
    <% end %>
        </nav>
        <section id="bg">
          <div class="container" id="main_container">
          <%= yield %>
          </div>
        </section>

    <% unless params[:controller] == "restaurants" && params[:action] == "index" %>
      <footer>
        <div>This app was made by the students of 2 Commit 2 Git</div>
      </footer>
    <% end %>
  </body>
</html>



<!-- {"controller"=>"restaurants", "action"=>"index"} -->

27-CSS/taco-tracker/app/views/tacos/_taco_form.html.erb
<% if @taco.errors %>
    <ul>
        <% @taco.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
    </ul>
<% end %>

<%= form_for @taco do |f| %>
    <%= f.label :name, "Taco Name" %>
    <%= f.text_field :name %>
    <%= f.label :price %>
    <%= f.number_field :price, min: 0, step: 0.01 %>
    <%= f.label :vegetarian %>

    <%= f.radio_button :vegetarian, true %>
    <span>True</span>
    <%= f.radio_button :vegetarian, false %>
    <span>False</span>

    <%= f.collection_select(:restaurant_id, Restaurant.all, :id, :display_name_and_city) %>


    <div>Ingredients:</div>
    <div>
        <%= f.collection_check_boxes(:ingredient_ids, Ingredient.all, :id, :name) %>


    </div>
    <%= f.submit local_assigns.fetch(:submit_text, "Submit") %>
<% end %>

27-CSS/taco-tracker/app/views/tacos/edit.html.erb
<h1>Edit this taco</h1>

<%= render partial: "taco_form", locals: {submit_text: "Change a Taco"} %>

27-CSS/taco-tracker/app/views/tacos/index.html.erb
<h1 class="title is-1">All Tacos</h1>

<% if flash[:message] %>
    <div class="error"><%= flash[:message] %></div>
<% end %>
<%= form_tag tacos_path, method: "GET" do %>
    <%= radio_button_tag 'vegetarian', 'true' %>
    <%= label_tag "Only Vegetarian"%>
    <%= radio_button_tag 'vegetarian', 'false' %>
    <%= label_tag "Only Meat"%>
    <%= radio_button_tag 'vegetarian', 'all' %>
    <%= label_tag "All Tacos" %>
    <%= submit_tag "Filter", class: 'button is-primary' %>
<% end %>

<%
=begin%>
 <div>
    <div>My favorite taco is <%= cookies["favorite_taco"] %></div>
    <div>The last taco I visited is <%= cookies["last_visited"] %></div>
    <div>My secret favorite taco is <%= session["secret_favorite"] %></div>
</div> 
<%
=end%>






<ul>
    <% @tacos.each do |taco| %>
        <li><%= link_to "#{taco.display_name}", taco_path(taco.id), class: taco.veg_color %></li>
    <% end %>
</ul>

27-CSS/taco-tracker/app/views/tacos/new.html.erb
<h1>Create a new taco</h1>



<%= render partial: "taco_form" %>

27-CSS/taco-tracker/app/views/tacos/show.html.erb
<h1>Detail Page</h1>

<div>Name: <%= @taco.display_name %></div>

<% if @taco.restaurant %>
    <div>Served at: <%= link_to @taco.restaurant.name, restaurant_path(@taco.restaurant.id) %></div>
<% end %>


<div>Price: <%= number_to_currency(@taco.price) %></div>
<div>Vegetarian:  <%= @taco.vegetarian %></div>

<% if @taco.ingredients %>
    <% @taco.ingredients.each do |ingredient| %>
        <div><%= ingredient.name %></div>
    <% end %>
<% end %>


<div>
<%= link_to "All Tacos", tacos_path %>
</div>

<div>
<%= link_to "Edit this taco", edit_taco_path(@taco.id) %>
<%= link_to "Delete this taco", taco_path(@taco.id), :method => :delete, data: {confirm: "Are you sure?"} %>
</div>