24-cosmic_travel/config/routes.rb
Rails.application.routes.draw do
  resources :planets
  resources :scientists
  resources :missions, only: [:new, :create]

  get "/about", to: "application#about_page"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

24-cosmic_travel/app/models/mission.rb
class Mission < ApplicationRecord
    belongs_to :scientist
    belongs_to :planet
end

24-cosmic_travel/app/models/planet.rb
class Planet < ApplicationRecord
    has_many :missions
    has_many :scientists, through: :missions

    def planet_plus_cheese
        self.name + " cheese"
    end
end

24-cosmic_travel/app/models/scientist.rb
class Scientist < ApplicationRecord
    has_many :missions
    has_many :planets, through: :missions

    validates :name, presence: true, uniqueness: {case_sensitive: false}
    validates :field_of_study, presence: true
    
end

24-cosmic_travel/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    def about_page
        @num_scientists = Scientist.count
        @num_planets = Planet.count
        render :about
    end
end

24-cosmic_travel/app/controllers/missions_controller.rb
class MissionsController < ApplicationController
  def new
    @mission = Mission.new
  end

  def create
    mission = Mission.create(mission_params)
    redirect_to scientist_path(mission.scientist.id)
  end

  private

  def mission_params
    params.require(:mission).permit(:scientist_id, :planet_id, :name)
  end
end

24-cosmic_travel/app/controllers/planets_controller.rb
class PlanetsController < ApplicationController
  before_action :set_planet, only: [:show, :edit, :update, :destroy]

  # GET /planets
  # GET /planets.json
  def index
    @planets = Planet.all
  end

  # GET /planets/1
  # GET /planets/1.json
  def show
  end

  # GET /planets/new
  def new
    @planet = Planet.new
  end

  # GET /planets/1/edit
  def edit
  end

  # POST /planets
  # POST /planets.json
  def create
    @planet = Planet.new(planet_params)

    respond_to do |format|
      if @planet.save
        format.html { redirect_to @planet, notice: 'Planet was successfully created.' }
        format.json { render :show, status: :created, location: @planet }
      else
        format.html { render :new }
        format.json { render json: @planet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /planets/1
  # PATCH/PUT /planets/1.json
  def update
    respond_to do |format|
      if @planet.update(planet_params)
        format.html { redirect_to @planet, notice: 'Planet was successfully updated.' }
        format.json { render :show, status: :ok, location: @planet }
      else
        format.html { render :edit }
        format.json { render json: @planet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /planets/1
  # DELETE /planets/1.json
  def destroy
    @planet.destroy
    respond_to do |format|
      format.html { redirect_to planets_url, notice: 'Planet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_planet
      @planet = Planet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def planet_params
      params.require(:planet).permit(:name, :distance_from_earth, :nearest_star)
    end
end

24-cosmic_travel/app/controllers/scientists_controller.rb
class ScientistsController < ApplicationController
  def index
    @scientists = Scientist.all

  end

  def show
    @scientist = Scientist.find(params[:id])
  end

  def new
    @scientist = Scientist.new

  end


  def create
    @scientist = Scientist.create(sci_params)
    if @scientist.valid?
        redirect_to scientist_path(@scientist.id)
    else
        render :new
    end
  end

  def edit
    @scientist = Scientist.find(params[:id])
  end

  def update
    @scientist = Scientist.find(params[:id])
    @scientist.update(sci_params)
    if @scientist.valid?
        redirect_to scientist_path(@scientist.id)
    else
        render :edit
    end

  end

  def destroy
    @scientist = Scientist.find(params[:id])
    @scientist.destroy
    redirect_to scientists_path
  end

  private

  def sci_params
    params.require(:scientist).permit(:name, :field_of_study)
  end
end

24-cosmic_travel/app/helpers/missions_helper.rb
module MissionsHelper
end

24-cosmic_travel/app/helpers/planets_helper.rb
module PlanetsHelper
end

24-cosmic_travel/app/helpers/scientists_helper.rb
module ScientistsHelper
end

24-cosmic_travel/app/views/application/about.html.erb
<h1>About my app</h1>

<div>Scientists: <%= @num_scientists %></div>
<div>Planets: <%= @num_planets %></div>

24-cosmic_travel/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cosmic travel agency</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

24-cosmic_travel/app/views/missions/new.html.erb
<h1>Create a new mission</h1>

<%= form_for @mission do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.collection_select :planet_id, Planet.all, :id, :planet_plus_cheese %>
    <%= f.collection_select :scientist_id, Scientist.all, :id, :name %>
    <%= f.submit %> 
<% end %>

24-cosmic_travel/app/views/scientists/_scientist_form.html.erb
<% if @scientist.errors %>
    <ul>
        <% @scientist.errors.full_messages.each do |message|%>
            <li><%= message %></li>
        <% end %>
    </ul>
<% end %>

<%= form_for @scientist do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :field_of_study %>
    <%= f.text_field :field_of_study %>
    <%= f.submit %>

<% end %>

24-cosmic_travel/app/views/scientists/edit.html.erb
<h1>Edit this scientist</h1>

<%= render partial: "scientist_form" %>

24-cosmic_travel/app/views/scientists/index.html.erb
<h1>All Scientists</h1>


<ul>
    <% @scientists.each do |scientist| %>   
        
        <li><%= link_to scientist.name, scientist_path(scientist.id) %></li>

    <% end %>
</ul>

24-cosmic_travel/app/views/scientists/new.html.erb
<h1>Create a new scientist</h1>


<%= render partial: "scientist_form" %>

24-cosmic_travel/app/views/scientists/show.html.erb
<h1><%= @scientist.name %></h1>


<div>
    <% @scientist.planets.each do |planet| %>
        <div><%= link_to planet.name, planet_path(planet.id) %></div>
    <% end %>
</div>


<%= button_to "Delete this scientist", scientist_path(@scientist.id), method: :delete %>